const fetch = require('node-fetch');

async function postBlogToLevitate(title, content, imageUrl) {
  console.log('📧 Sending blog to Tammy for Levitate posting...');
  
  const emailBody = `
Hi Tammy,

A new blog post has been automatically generated and is ready to post to the My Texas Estate Plan website via Levitate.

STEPS:
1. Log into Levitate at secure.levitate.ai
2. Go to Campaigns → Blogs
3. Click "Create New Blog Post"
4. Copy the title and content below
5. Add an image and schedule it

---
BLOG TITLE:
${title}

---
BLOG CONTENT:
${content}

---
IMAGE URL (download and upload to Levitate):
${imageUrl || 'No image — search Pexels for a relevant estate planning image'}

---
This blog was auto-generated by the My Texas Estate Plan content system.
`;

  // Send via SendGrid or direct SMTP
  // Using a simple fetch to a free email API
  try {
    // Try using Gmail webhook via Google Apps Script
    const webhookUrl = process.env.EMAIL_WEBHOOK;
    
    if (webhookUrl) {
      const response = await fetch(webhookUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
  type: 'email',
  to: process.env.NOTIFICATION_EMAIL || 'tammy@mytxestateplan.com',
  subject: `📝 New Blog Ready to Post: ${title}`,
  body: emailBody
})
      });
      const text = await response.text();
      console.log('✅ Email sent to Tammy:', text);
    } else {
      console.log('⚠️ EMAIL_WEBHOOK not set — blog content:');
      console.log('Title:', title);
      console.log('Content preview:', content.substring(0, 200));
    }
    
    return true;
  } catch (err) {
    console.error('❌ Email failed:', err.message);
    throw err;
  }
}

module.exports = { postBlogToLevitate };